# -*- coding: utf-8 -*-
"""reg_lineal_housing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yQiLkIcX6HOi0adca1CVtcLlNGOZ4Pa6

# Regresión Lineal — California Housing
**Dataset real de internet:** California Housing (censo 1990)

- `m = 20,640` muestras  
- `n = 12` features  
- **Prediccion:** `Price` (precio de vivienda en USD)
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
from matplotlib import pyplot
from mpl_toolkits.mplot3d import Axes3D
# %matplotlib inline

"""## 1. Cargar Dataset con Pandas
> Dataset: California Housing — descargable desde:
> `https://raw.githubusercontent.com/ageron/handson-ml2/master/datasets/housing/housing.csv`
"""

from google.colab import drive
drive.mount('/content/gdrive')

# Leer CSV con Pandas
#df = pd.read_csv('california_housing.csv')                    # local
df = pd.read_csv('/content/gdrive/MyDrive/Universida/IA/Dataset/california_housing.csv')  # Colab

m, n = df.shape[0], df.shape[1] - 1
print(f'Dataset: m={m} muestras, n={n} features')
df.describe().round(2)

#esta linea

print("Tipos de datos de cada característica:")
display(df.dtypes)

print("\nInformación completa del DataFrame:")
df.info()

print("Recuento de valores nulos por característica:")
display(df.isnull().sum())

"""## 2. Preprocesamiento con Pandas"""

df.dropna(inplace=True)                                          # eliminar nulos
df = df.clip(lower=df.quantile(0.01), upper=df.quantile(0.99), axis=1)  # recortar outliers

X_pd = df.drop(columns='Price').values
y_pd = df['Price'].values
m, n = X_pd.shape
print(f'Tras preprocesamiento: m={m}, n={n}')

"""## 3. Normalización + columna de unos (θ₀)"""

mu, sigma = X_pd.mean(axis=0), X_pd.std(axis=0)
X_norm    = (X_pd - mu) / sigma
X_b       = np.hstack([np.ones((m, 1)), X_norm])   # agrega columna de unos
print(f'X_b shape: {X_b.shape}')

"""## 4. Función de Costo y Descenso por Gradiente"""

def calcularCosto(X, y, theta):
    return (1 / (2 * len(y))) * np.sum(np.square(X @ theta - y))

def gradientDescent(X, y, theta, alpha, num_iters):
    theta, J_history = theta.copy(), []
    for _ in range(num_iters):
        theta    -= (alpha / len(y)) * (X @ theta - y) @ X
        J_history.append(calcularCosto(X, y, theta))
    return theta, J_history

"""## 5. Entrenamiento"""

theta             = np.zeros(n + 1)
theta, J_history  = gradientDescent(X_b, y_pd, theta, alpha=0.1, num_iters=500)

print(f'Costo inicial : {J_history[0]:.2f}')
print(f'Costo final   : {J_history[-1]:.2f}')
print(f'Reducción     : {(1 - J_history[-1]/J_history[0])*100:.1f}%')

"""## 6. Inferencia con Pandas"""

# Tomar 3 muestras nuevas directamente desde el DataFrame
muestra      = df.drop(columns='Price').iloc[:3]
muestra_norm = (muestra.values - mu) / sigma
muestra_b    = np.hstack([np.ones((3, 1)), muestra_norm])
predicciones = muestra_b @ theta

print('Inferencia (3 viviendas):')
reales = df['Price'].iloc[:3].values
[print(f'  Casa {i+1} | Real: ${reales[i]:,.0f}  →  Predicho: ${p:,.0f}') for i, p in enumerate(predicciones)]

"""## 7. Gráficas"""

fig, axes = pyplot.subplots(1, 2, figsize=(13, 4))

# Convergencia del costo
axes[0].plot(np.arange(len(J_history)), J_history, lw=2, color='steelblue')
axes[0].set(xlabel='Número de iteraciones', ylabel='Costo J', title='Convergencia del costo')
axes[0].grid(True)

# Real vs Predicho
y_pred_full = X_b @ theta
axes[1].scatter(y_pd, y_pred_full, alpha=0.1, s=4, color='royalblue')
lims = [y_pd.min(), y_pd.max()]
axes[1].plot(lims, lims, 'r--', lw=1.5)
axes[1].set(xlabel='Precio real (USD)', ylabel='Precio predicho (USD)', title='Real vs Predicho')
axes[1].grid(True)

pyplot.tight_layout()
pyplot.show()